// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: cmd/testserver/hello/hello.proto

package hellov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_cmd_testserver_hello_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_testserver_hello_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_cmd_testserver_hello_hello_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_cmd_testserver_hello_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_testserver_hello_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_cmd_testserver_hello_hello_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_cmd_testserver_hello_hello_proto protoreflect.FileDescriptor

const file_cmd_testserver_hello_hello_proto_rawDesc = "" +
	"\n" +
	" cmd/testserver/hello/hello.proto\x12\bhello.v1\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2O\n" +
	"\fHelloService\x12?\n" +
	"\vHelloStream\x12\x16.hello.v1.HelloRequest\x1a\x14.hello.v1.HelloReply(\x010\x01B\xa2\x01\n" +
	"\fcom.hello.v1B\n" +
	"HelloProtoP\x01ZEgithub.com/prnvbn/grpcexp/cmd/testserver/cmd/testserver/hello;hellov1\xa2\x02\x03HXX\xaa\x02\bHello.V1\xca\x02\bHello\\V1\xe2\x02\x14Hello\\V1\\GPBMetadata\xea\x02\tHello::V1b\x06proto3"

var (
	file_cmd_testserver_hello_hello_proto_rawDescOnce sync.Once
	file_cmd_testserver_hello_hello_proto_rawDescData []byte
)

func file_cmd_testserver_hello_hello_proto_rawDescGZIP() []byte {
	file_cmd_testserver_hello_hello_proto_rawDescOnce.Do(func() {
		file_cmd_testserver_hello_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_testserver_hello_hello_proto_rawDesc), len(file_cmd_testserver_hello_hello_proto_rawDesc)))
	})
	return file_cmd_testserver_hello_hello_proto_rawDescData
}

var file_cmd_testserver_hello_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cmd_testserver_hello_hello_proto_goTypes = []any{
	(*HelloRequest)(nil), // 0: hello.v1.HelloRequest
	(*HelloReply)(nil),   // 1: hello.v1.HelloReply
}
var file_cmd_testserver_hello_hello_proto_depIdxs = []int32{
	0, // 0: hello.v1.HelloService.HelloStream:input_type -> hello.v1.HelloRequest
	1, // 1: hello.v1.HelloService.HelloStream:output_type -> hello.v1.HelloReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_testserver_hello_hello_proto_init() }
func file_cmd_testserver_hello_hello_proto_init() {
	if File_cmd_testserver_hello_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_testserver_hello_hello_proto_rawDesc), len(file_cmd_testserver_hello_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_testserver_hello_hello_proto_goTypes,
		DependencyIndexes: file_cmd_testserver_hello_hello_proto_depIdxs,
		MessageInfos:      file_cmd_testserver_hello_hello_proto_msgTypes,
	}.Build()
	File_cmd_testserver_hello_hello_proto = out.File
	file_cmd_testserver_hello_hello_proto_goTypes = nil
	file_cmd_testserver_hello_hello_proto_depIdxs = nil
}
