// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: cmd/testserver/echo/echo.proto

package echov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message_Enum int32

const (
	Message_ENUM_UNSPECIFIED Message_Enum = 0
	Message_ENUM_VALUE_1     Message_Enum = 1
	Message_ENUM_VALUE_2     Message_Enum = 2
)

// Enum value maps for Message_Enum.
var (
	Message_Enum_name = map[int32]string{
		0: "ENUM_UNSPECIFIED",
		1: "ENUM_VALUE_1",
		2: "ENUM_VALUE_2",
	}
	Message_Enum_value = map[string]int32{
		"ENUM_UNSPECIFIED": 0,
		"ENUM_VALUE_1":     1,
		"ENUM_VALUE_2":     2,
	}
)

func (x Message_Enum) Enum() *Message_Enum {
	p := new(Message_Enum)
	*p = x
	return p
}

func (x Message_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_testserver_echo_echo_proto_enumTypes[0].Descriptor()
}

func (Message_Enum) Type() protoreflect.EnumType {
	return &file_cmd_testserver_echo_echo_proto_enumTypes[0]
}

func (x Message_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_Enum.Descriptor instead.
func (Message_Enum) EnumDescriptor() ([]byte, []int) {
	return file_cmd_testserver_echo_echo_proto_rawDescGZIP(), []int{2, 0}
}

type EvenMoreNestedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Boolean       bool                   `protobuf:"varint,2,opt,name=boolean,proto3" json:"boolean,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvenMoreNestedMessage) Reset() {
	*x = EvenMoreNestedMessage{}
	mi := &file_cmd_testserver_echo_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvenMoreNestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvenMoreNestedMessage) ProtoMessage() {}

func (x *EvenMoreNestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_testserver_echo_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvenMoreNestedMessage.ProtoReflect.Descriptor instead.
func (*EvenMoreNestedMessage) Descriptor() ([]byte, []int) {
	return file_cmd_testserver_echo_echo_proto_rawDescGZIP(), []int{0}
}

func (x *EvenMoreNestedMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EvenMoreNestedMessage) GetBoolean() bool {
	if x != nil {
		return x.Boolean
	}
	return false
}

type NestedMessage struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Message                 string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Boolean                 bool                   `protobuf:"varint,2,opt,name=boolean,proto3" json:"boolean,omitempty"`
	Int32Value              int32                  `protobuf:"varint,3,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	EvenMoreNestedMessage   *EvenMoreNestedMessage `protobuf:"bytes,4,opt,name=even_more_nested_message,json=evenMoreNestedMessage,proto3" json:"even_more_nested_message,omitempty"`
	EvenMoreNestedMessage_2 *EvenMoreNestedMessage `protobuf:"bytes,5,opt,name=even_more_nested_message_2,json=evenMoreNestedMessage2,proto3" json:"even_more_nested_message_2,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *NestedMessage) Reset() {
	*x = NestedMessage{}
	mi := &file_cmd_testserver_echo_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedMessage) ProtoMessage() {}

func (x *NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_testserver_echo_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedMessage.ProtoReflect.Descriptor instead.
func (*NestedMessage) Descriptor() ([]byte, []int) {
	return file_cmd_testserver_echo_echo_proto_rawDescGZIP(), []int{1}
}

func (x *NestedMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NestedMessage) GetBoolean() bool {
	if x != nil {
		return x.Boolean
	}
	return false
}

func (x *NestedMessage) GetInt32Value() int32 {
	if x != nil {
		return x.Int32Value
	}
	return 0
}

func (x *NestedMessage) GetEvenMoreNestedMessage() *EvenMoreNestedMessage {
	if x != nil {
		return x.EvenMoreNestedMessage
	}
	return nil
}

func (x *NestedMessage) GetEvenMoreNestedMessage_2() *EvenMoreNestedMessage {
	if x != nil {
		return x.EvenMoreNestedMessage_2
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Boolean       bool                   `protobuf:"varint,2,opt,name=boolean,proto3" json:"boolean,omitempty"`
	Enum          Message_Enum           `protobuf:"varint,3,opt,name=enum,proto3,enum=echo.v1.Message_Enum" json:"enum,omitempty"`
	Int32Value    int32                  `protobuf:"varint,4,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Int64Value    int64                  `protobuf:"varint,5,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	FloatValue    float32                `protobuf:"fixed32,6,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	DoubleValue   float64                `protobuf:"fixed64,7,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	Strings       []string               `protobuf:"bytes,8,rep,name=strings,proto3" json:"strings,omitempty"`
	NestedMessage *NestedMessage         `protobuf:"bytes,9,opt,name=nested_message,json=nestedMessage,proto3" json:"nested_message,omitempty"`
	MapValue      map[string]string      `protobuf:"bytes,10,rep,name=map_value,json=mapValue,proto3" json:"map_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_cmd_testserver_echo_echo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_testserver_echo_echo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_cmd_testserver_echo_echo_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Message) GetBoolean() bool {
	if x != nil {
		return x.Boolean
	}
	return false
}

func (x *Message) GetEnum() Message_Enum {
	if x != nil {
		return x.Enum
	}
	return Message_ENUM_UNSPECIFIED
}

func (x *Message) GetInt32Value() int32 {
	if x != nil {
		return x.Int32Value
	}
	return 0
}

func (x *Message) GetInt64Value() int64 {
	if x != nil {
		return x.Int64Value
	}
	return 0
}

func (x *Message) GetFloatValue() float32 {
	if x != nil {
		return x.FloatValue
	}
	return 0
}

func (x *Message) GetDoubleValue() float64 {
	if x != nil {
		return x.DoubleValue
	}
	return 0
}

func (x *Message) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

func (x *Message) GetNestedMessage() *NestedMessage {
	if x != nil {
		return x.NestedMessage
	}
	return nil
}

func (x *Message) GetMapValue() map[string]string {
	if x != nil {
		return x.MapValue
	}
	return nil
}

var File_cmd_testserver_echo_echo_proto protoreflect.FileDescriptor

const file_cmd_testserver_echo_echo_proto_rawDesc = "" +
	"\n" +
	"\x1ecmd/testserver/echo/echo.proto\x12\aecho.v1\"K\n" +
	"\x15EvenMoreNestedMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\aboolean\x18\x02 \x01(\bR\aboolean\"\x99\x02\n" +
	"\rNestedMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\aboolean\x18\x02 \x01(\bR\aboolean\x12\x1f\n" +
	"\vint32_value\x18\x03 \x01(\x05R\n" +
	"int32Value\x12W\n" +
	"\x18even_more_nested_message\x18\x04 \x01(\v2\x1e.echo.v1.EvenMoreNestedMessageR\x15evenMoreNestedMessage\x12Z\n" +
	"\x1aeven_more_nested_message_2\x18\x05 \x01(\v2\x1e.echo.v1.EvenMoreNestedMessageR\x16evenMoreNestedMessage2\"\x83\x04\n" +
	"\aMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\aboolean\x18\x02 \x01(\bR\aboolean\x12)\n" +
	"\x04enum\x18\x03 \x01(\x0e2\x15.echo.v1.Message.EnumR\x04enum\x12\x1f\n" +
	"\vint32_value\x18\x04 \x01(\x05R\n" +
	"int32Value\x12\x1f\n" +
	"\vint64_value\x18\x05 \x01(\x03R\n" +
	"int64Value\x12\x1f\n" +
	"\vfloat_value\x18\x06 \x01(\x02R\n" +
	"floatValue\x12!\n" +
	"\fdouble_value\x18\a \x01(\x01R\vdoubleValue\x12\x18\n" +
	"\astrings\x18\b \x03(\tR\astrings\x12=\n" +
	"\x0enested_message\x18\t \x01(\v2\x16.echo.v1.NestedMessageR\rnestedMessage\x12;\n" +
	"\tmap_value\x18\n" +
	" \x03(\v2\x1e.echo.v1.Message.MapValueEntryR\bmapValue\x1a;\n" +
	"\rMapValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x04Enum\x12\x14\n" +
	"\x10ENUM_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fENUM_VALUE_1\x10\x01\x12\x10\n" +
	"\fENUM_VALUE_2\x10\x0229\n" +
	"\vEchoService\x12*\n" +
	"\x04Echo\x12\x10.echo.v1.Message\x1a\x10.echo.v1.MessageB\x9c\x01\n" +
	"\vcom.echo.v1B\tEchoProtoP\x01ZCgithub.com/prnvbn/grpcexp/cmd/testserver/cmd/testserver/echo;echov1\xa2\x02\x03EXX\xaa\x02\aEcho.V1\xca\x02\bEcho_\\V1\xe2\x02\x14Echo_\\V1\\GPBMetadata\xea\x02\bEcho::V1b\x06proto3"

var (
	file_cmd_testserver_echo_echo_proto_rawDescOnce sync.Once
	file_cmd_testserver_echo_echo_proto_rawDescData []byte
)

func file_cmd_testserver_echo_echo_proto_rawDescGZIP() []byte {
	file_cmd_testserver_echo_echo_proto_rawDescOnce.Do(func() {
		file_cmd_testserver_echo_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_testserver_echo_echo_proto_rawDesc), len(file_cmd_testserver_echo_echo_proto_rawDesc)))
	})
	return file_cmd_testserver_echo_echo_proto_rawDescData
}

var file_cmd_testserver_echo_echo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_testserver_echo_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cmd_testserver_echo_echo_proto_goTypes = []any{
	(Message_Enum)(0),             // 0: echo.v1.Message.Enum
	(*EvenMoreNestedMessage)(nil), // 1: echo.v1.EvenMoreNestedMessage
	(*NestedMessage)(nil),         // 2: echo.v1.NestedMessage
	(*Message)(nil),               // 3: echo.v1.Message
	nil,                           // 4: echo.v1.Message.MapValueEntry
}
var file_cmd_testserver_echo_echo_proto_depIdxs = []int32{
	1, // 0: echo.v1.NestedMessage.even_more_nested_message:type_name -> echo.v1.EvenMoreNestedMessage
	1, // 1: echo.v1.NestedMessage.even_more_nested_message_2:type_name -> echo.v1.EvenMoreNestedMessage
	0, // 2: echo.v1.Message.enum:type_name -> echo.v1.Message.Enum
	2, // 3: echo.v1.Message.nested_message:type_name -> echo.v1.NestedMessage
	4, // 4: echo.v1.Message.map_value:type_name -> echo.v1.Message.MapValueEntry
	3, // 5: echo.v1.EchoService.Echo:input_type -> echo.v1.Message
	3, // 6: echo.v1.EchoService.Echo:output_type -> echo.v1.Message
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cmd_testserver_echo_echo_proto_init() }
func file_cmd_testserver_echo_echo_proto_init() {
	if File_cmd_testserver_echo_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_testserver_echo_echo_proto_rawDesc), len(file_cmd_testserver_echo_echo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_testserver_echo_echo_proto_goTypes,
		DependencyIndexes: file_cmd_testserver_echo_echo_proto_depIdxs,
		EnumInfos:         file_cmd_testserver_echo_echo_proto_enumTypes,
		MessageInfos:      file_cmd_testserver_echo_echo_proto_msgTypes,
	}.Build()
	File_cmd_testserver_echo_echo_proto = out.File
	file_cmd_testserver_echo_echo_proto_goTypes = nil
	file_cmd_testserver_echo_echo_proto_depIdxs = nil
}
