// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: cmd/testserver/echo/echo.proto

package echov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message_Enum int32

const (
	Message_ENUM_UNSPECIFIED Message_Enum = 0
	Message_ENUM_VALUE_1     Message_Enum = 1
	Message_ENUM_VALUE_2     Message_Enum = 2
)

// Enum value maps for Message_Enum.
var (
	Message_Enum_name = map[int32]string{
		0: "ENUM_UNSPECIFIED",
		1: "ENUM_VALUE_1",
		2: "ENUM_VALUE_2",
	}
	Message_Enum_value = map[string]int32{
		"ENUM_UNSPECIFIED": 0,
		"ENUM_VALUE_1":     1,
		"ENUM_VALUE_2":     2,
	}
)

func (x Message_Enum) Enum() *Message_Enum {
	p := new(Message_Enum)
	*p = x
	return p
}

func (x Message_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_testserver_echo_echo_proto_enumTypes[0].Descriptor()
}

func (Message_Enum) Type() protoreflect.EnumType {
	return &file_cmd_testserver_echo_echo_proto_enumTypes[0]
}

func (x Message_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_Enum.Descriptor instead.
func (Message_Enum) EnumDescriptor() ([]byte, []int) {
	return file_cmd_testserver_echo_echo_proto_rawDescGZIP(), []int{0, 0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Boolean       bool                   `protobuf:"varint,2,opt,name=boolean,proto3" json:"boolean,omitempty"`
	Enum          Message_Enum           `protobuf:"varint,3,opt,name=enum,proto3,enum=echo.v1.Message_Enum" json:"enum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_cmd_testserver_echo_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_testserver_echo_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_cmd_testserver_echo_echo_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Message) GetBoolean() bool {
	if x != nil {
		return x.Boolean
	}
	return false
}

func (x *Message) GetEnum() Message_Enum {
	if x != nil {
		return x.Enum
	}
	return Message_ENUM_UNSPECIFIED
}

var File_cmd_testserver_echo_echo_proto protoreflect.FileDescriptor

const file_cmd_testserver_echo_echo_proto_rawDesc = "" +
	"\n" +
	"\x1ecmd/testserver/echo/echo.proto\x12\aecho.v1\"\xaa\x01\n" +
	"\aMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\aboolean\x18\x02 \x01(\bR\aboolean\x12)\n" +
	"\x04enum\x18\x03 \x01(\x0e2\x15.echo.v1.Message.EnumR\x04enum\"@\n" +
	"\x04Enum\x12\x14\n" +
	"\x10ENUM_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fENUM_VALUE_1\x10\x01\x12\x10\n" +
	"\fENUM_VALUE_2\x10\x0229\n" +
	"\vEchoService\x12*\n" +
	"\x04Echo\x12\x10.echo.v1.Message\x1a\x10.echo.v1.MessageB\x9c\x01\n" +
	"\vcom.echo.v1B\tEchoProtoP\x01ZCgithub.com/prnvbn/grpcexp/cmd/testserver/cmd/testserver/echo;echov1\xa2\x02\x03EXX\xaa\x02\aEcho.V1\xca\x02\bEcho_\\V1\xe2\x02\x14Echo_\\V1\\GPBMetadata\xea\x02\bEcho::V1b\x06proto3"

var (
	file_cmd_testserver_echo_echo_proto_rawDescOnce sync.Once
	file_cmd_testserver_echo_echo_proto_rawDescData []byte
)

func file_cmd_testserver_echo_echo_proto_rawDescGZIP() []byte {
	file_cmd_testserver_echo_echo_proto_rawDescOnce.Do(func() {
		file_cmd_testserver_echo_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_testserver_echo_echo_proto_rawDesc), len(file_cmd_testserver_echo_echo_proto_rawDesc)))
	})
	return file_cmd_testserver_echo_echo_proto_rawDescData
}

var file_cmd_testserver_echo_echo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_testserver_echo_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cmd_testserver_echo_echo_proto_goTypes = []any{
	(Message_Enum)(0), // 0: echo.v1.Message.Enum
	(*Message)(nil),   // 1: echo.v1.Message
}
var file_cmd_testserver_echo_echo_proto_depIdxs = []int32{
	0, // 0: echo.v1.Message.enum:type_name -> echo.v1.Message.Enum
	1, // 1: echo.v1.EchoService.Echo:input_type -> echo.v1.Message
	1, // 2: echo.v1.EchoService.Echo:output_type -> echo.v1.Message
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cmd_testserver_echo_echo_proto_init() }
func file_cmd_testserver_echo_echo_proto_init() {
	if File_cmd_testserver_echo_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_testserver_echo_echo_proto_rawDesc), len(file_cmd_testserver_echo_echo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_testserver_echo_echo_proto_goTypes,
		DependencyIndexes: file_cmd_testserver_echo_echo_proto_depIdxs,
		EnumInfos:         file_cmd_testserver_echo_echo_proto_enumTypes,
		MessageInfos:      file_cmd_testserver_echo_echo_proto_msgTypes,
	}.Build()
	File_cmd_testserver_echo_echo_proto = out.File
	file_cmd_testserver_echo_echo_proto_goTypes = nil
	file_cmd_testserver_echo_echo_proto_depIdxs = nil
}
